---
title: "Final_Draft"
author: "Esme, Zach, & Mandi"
date: "2/21/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(edld652)
library(tidyverse)
library(janitor)
library(here)
library(rio)
library(ggtext)
library(ggiraph)
library(scales)
library(gghighlight)
library(writexl)
library(colorspace)
library(maps)
library(albersusa)
library(cowplot)
```

```{r load-data}
######## Load CLASS data, clean, & select columns ########################
class <- import(here("data", "Class20032019.xlsx")) %>% 
  janitor::clean_names() # CLASS Data Set

class <- class %>% 
  rename(fips = stfips,
         state_abbr = state) # make class data a fips to match grad_rates df, same with the state abbreviation.

class <- class %>% 
  select(1:3, 6, 18, 47)

######## Load grad_rates, clean, & select columns ##########################
grad_rates <- get_data("EDFacts_acgr_lea_2011_2019") %>% 
  janitor::clean_names() # graduation rates (and cohorts)

grad_rates <- grad_rates %>% 
  mutate(fips = readr::parse_number(fipst)) #rename fipst to fips

grad_rates <- grad_rates %>% 
  select(1:8, 10, 12:27, 30)

####### Merge CLASS with grad_rates df ######################################
class_grads <- left_join(grad_rates, class, by = "fips") # class df w/ grad rates&state

####### Load state_info, clean, & select columns ############################
state_info <- readr::read_csv("https://github.com/kjhealy/fips-codes/raw/master/state_fips_master.csv") #state data with fipst

state_info <- subset(state_info, select = c(1, 4, 6, 7, 9, 10))
# just want the columns with unrepeated information to class_grad that can be used later (example: regions and divisions)
state_info <- state_info %>% 
   mutate(state_name = tolower(state_name)) %>% 
    rename(state = state_name)


###### Merge class_grads with state_info data ##################################
data <- left_join(class_grads, state_info) # this has grad rates and state info
```

```{r fiscal-data}
## commenting out fiscal data other than 2011 for now ###################
## trying out visual with just one then will work to merge later ########

#fiscal10 <- get_data("NCES_CCD_fiscal_district_2010") %>% 
#  janitor::clean_names() %>% 
#  select(leaid, fipst, stabbr, totalrev, tfedrev,
#         tstrev, tlocrev, tcurinst, tcurssvc)

fiscal11 <- get_data("NCES_CCD_fiscal_district_2011") %>% 
  janitor::clean_names() %>% 
  select(leaid, fipst, stabbr, totalrev, tfedrev,
         tstrev, tlocrev, tcurinst, tcurssvc)

#fiscal12 <- get_data("NCES_CCD_fiscal_district_2012") %>% 
 # janitor::clean_names() %>% 
#  select(leaid, fipst, stabbr, totalrev, tfedrev,
 #        tstrev, tlocrev, tcurinst, tcurssvc)

#fiscal13 <- get_data("NCES_CCD_fiscal_district_2013") %>% 
 # janitor::clean_names() %>% 
  #select(leaid, fipst, stabbr, totalrev, tfedrev,
   #      tstrev, tlocrev, tcurinst, tcurssvc)

#fiscal14 <- get_data("NCES_CCD_fiscal_district_2014") %>% 
 # janitor::clean_names() %>% 
  #select(leaid, fipst, stabbr, totalrev, tfedrev,
   #      tstrev, tlocrev, tcurinst, tcurssvc)

#fiscal15 <- get_data("NCES_CCD_fiscal_district_2015") %>% 
 # janitor::clean_names() %>% 
  #select(leaid, fipst, stabbr, totalrev, tfedrev,
   #      tstrev, tlocrev, tcurinst, tcurssvc)

#fiscal16 <- get_data("NCES_CCD_fiscal_district_2016") %>% 
 # janitor::clean_names() %>% 
  #select(leaid, fipst, stabbr, totalrev, tfedrev,
   #      tstrev, tlocrev, tcurinst, tcurssvc)

#fiscal17 <- get_data("NCES_CCD_fiscal_district_2017") %>% 
 # janitor::clean_names() %>% 
  #select(leaid, fipst, stabbr, totalrev, tfedrev,
   #      tstrev, tlocrev, tcurinst, tcurssvc)

#fiscal18 <- get_data("NCES_CCD_fiscal_district_2018") %>% 
 # janitor::clean_names() %>% 
  #select(leaid, fipst, stabbr, totalrev, tfedrev,
   #      tstrev, tlocrev, tcurinst, tcurssvc)


# Merge data (state_info, grads, and fiscal11)
state_grads <- left_join(state_info, grad_rates)

# Merge state_grads with fiscal11
fiscal11 <- fiscal11 %>% 
  mutate(fips = readr::parse_number(fipst)) #rename fipst to fips

data_viz3 <- left_join(state_grads, fiscal11)
```

**Visual for class draft assignment**
```{r viz-3-esme}
data_viz3 <- data_viz3 %>% 
  tidyr::separate(ecd_rate, c("lower", "upper"), sep = "-") %>% 
  filter(!grepl("G|L|P", lower)) %>% 
  mutate(
    upper = ifelse(is.na(upper), lower, upper),
    lower = as.numeric(lower),
    upper = as.numeric(upper)
  ) %>% 
  rowwise() %>% 
  mutate(mean = mean(c(lower, upper))) %>% 
  ungroup()

data_viz3 <- data_viz3 %>% 
  group_by(state, region_name) %>% 
  mutate(support_mean = mean(tcurssvc, na.rm = TRUE))

ggplot(data_viz3, aes(support_mean, mean)) +
  geom_point(color = "seagreen4") +
  gghighlight(stabbr == "OR") +
  scale_x_log10("Total Revenue for Support Services",
                labels = scales::dollar) +
  labs(y = "Averaege Graduation Rates",
       title = "Graduation Rates of Economically Disadvantaged Students",
       subtitle = "by Revenue for Support Services in Oregon",
       caption = "Data collected from 2011") +
  theme_minimal() +
  theme(axis.text.x = element_text(face = "bold"),
        axis.text.y = element_text(face = "bold"),
        axis.title.x = element_text(size = 14, face = "bold"),
        axis.title.y = element_text(size = 14, face = "bold"),
        plot.title = element_text(size = 16, face = "bold"),
        plot.subtitle = element_text(size = 11, face = "bold", hjust = 0))

### thinking to show various group rates vs each other (maybe?), maybe grouping into categorical variables since would love to make a heatmap but might not be the best visual for this data actually. Original idea for a heatmap was y = school district or state, x = revenue (make categorical?), and fill by HS grad rates ###################
```


<!-- trying something, Mandi this is the code I (Esme) showed you-->
```{r viz-code-for-part-of-Q1}
data_viz3 %>% 
  group_by(state, region_name) %>% 
  mutate(support_mean = mean(tcurssvc, na.rm = TRUE)) %>% 
  ggplot(aes(mean, state)) +
  geom_point(color = "seagreen4") +
  labs(y = "Averaege Graduation Rates",
       title = "Graduation Rates of Economically Disadvantaged Students",
       subtitle = "by state",
       caption = "Data collected from 2011") +
  theme_minimal() +
  theme(axis.text.x = element_text(face = "bold"),
        axis.text.y = element_text(face = "bold"),
        axis.title.x = element_text(size = 14, face = "bold"),
        axis.title.y = element_text(size = 14, face = "bold"),
        plot.title = element_text(size = 16, face = "bold"),
        plot.subtitle = element_text(size = 11, face = "bold", hjust = 0))
```

################################# ZACHS VIZ #############################################
For reviewer: Run each line of code in below ode chunks
```{r}
data.z <- data %>%
  separate(all_rate, c("lower", "upper"), sep = "-") %>% 
  filter(!grepl("G|L|P", lower)) %>%
  mutate(
    upper = ifelse(is.na(upper), lower, upper),
    lower = as.numeric(lower),
    upper = as.numeric(upper)
  ) %>% 
  rowwise() %>% 
  mutate(mean_rate = mean(c(lower, upper))) %>% 
  ungroup()

#data.z <- data.z %>% 
  #select(2,3,25:32, 39:41)
data.z <- data.z %>% 
  select(1:3, 25:32, 34:38)

data.z1 <- data.z %>% 
  group_by(stnam) %>% 
  summarize(state_avg = mean(mean_rate), # Collapse mean_rate by state to get only 1 mean value of grad rate for each state
            se = sd(mean_rate)/sqrt(n()))# get standard error of each state graduation average
data.z1$national_avg <- data.z1 %>% 
  summarize(national = mean(state_avg)) # getting national average for graduation rate

data.z1$se_national <- data.z1 %>% 
  summarize(se_national = sd(state_avg)/sqrt(n())) #getting SE of graduation rate for national average
```

This code chunk is the foundation of this data vizualization #1
```{r zviz-v1}
data.z1 %>% 
  mutate(stnam = fct_reorder(stnam, state_avg)) %>% 
  ggplot(aes(state_avg, stnam)) +
  geom_linerange(aes(xmin = state_avg - 1.96 * se,
                     xmax = state_avg + 1.96 * se),
                 color = "grey40") +
  geom_point() +
  theme_minimal()# shows state overall graduation rate with SE by state. . . 
```


__USE THIS AS V1 OF MY DATA VIZ__
```{r zviz-v2}
#regions_only <- data.z %>% 
  #select(3, 11, 12)
  #unique()
regions_only <- data.z %>% 
  select(4, 14, 15) %>% 
  unique()
z1.regions <- left_join(data.z1, regions_only, by = "stnam") #adding regions to df for plotting

z1.regions %>% 
  mutate(stnam = fct_reorder(stnam, state_avg)) %>% 
  ggplot(aes(state_avg, stnam, color = region_name)) +
  geom_linerange(aes(xmin = state_avg - 1.96 * se,
                     xmax = state_avg + 1.96 * se),
                 color = "grey40") +
  geom_point() +
   geom_vline(xintercept = 78.17352,
             color = "darkslateblue",
             linetype = "solid",
             size = 0.8) +
  theme_minimal() +
  labs(x = "Graduation Rate (%) - 2011",
       y = "",
       title = "State Graduation Rates",
       subtitle = "By Region",
       caption = "Vertical blue line indicates the graduation rate of the United States",
       color = "Region") 
```

```{r zviz-final-data}
class.z <- class %>% 
  group_by(year, state_abbr) %>% 
  summarize(avg_timehs2 = mean(timehs2) #adding in the CLASS data. The timehs2 variable relates to State Policies regarding PE time requirements for High School
)
#writexl::write_xlsx(class.z, here("data", "class.z.xlsx"))
class.z.2010 <- import(here("data", "class.z.2010.xlsx")) # data to merge into regions/graduation rates data

class.z.2010 <- left_join(z1.regions, class.z.2010) # joining
```


__USE THIS AS V2 OF MY PLOT__
```{r zviz-final-plot}
class.z.2010$avg_timehs2 = as.factor(class.z.2010$avg_timehs2)
# converting variable to a factor for analysis
class.z.2010 %>% 
  mutate(stnam = fct_reorder(stnam, state_avg)) %>% 
  ggplot(aes(state_avg, stnam, color = region_name, shape = avg_timehs2)) +
  geom_linerange(aes(xmin = state_avg - 1.96 * se,
                     xmax = state_avg + 1.96 * se),
                 color = "grey40") +
  geom_point(size = 3) +
  theme_minimal() +
  geom_vline(xintercept = 78.17352,
             color = "darkslateblue",
             linetype = "solid",
             size = 0.8) +
  geom_vline(xintercept = 76.14586,
             color = "red",
             linetype = "dashed",
             size = 0.5) +
  geom_vline(xintercept = 80.17532,
             color = "red",
             linetype = "dashed",
             size = 0.5) +
  coord_cartesian(xlim = c(60, 90)) +
  geom_text(aes(x = 79, y = 42,
                label = "National Average (78.2)"),
                size = 3,
                color = "darkslateblue",
                angle = 270, vjust = 1.2) +
  geom_text(aes(x = 75.25, y = 42,
                label = "Lower Limit (76.2)"),
                size = 3,
                color = "red",
                angle = 90, vjust = 1.2) +
  geom_text(aes(x = 81, y = 42,
                label = "Upper Limit (80.2)"),
                size = 3,
                color = "red",
                angle = 270, vjust = 1.2) + 
  theme(panel.grid.major.y = element_blank(), 
        panel.grid.major.x = element_line(color = "gray85"), 
        axis.title.x = element_text(face = "bold", size = 12),
        plot.title = element_text(hjust = .0, size = 14, face = "bold"), 
        plot.subtitle = element_text(hjust = -.16), 
        plot.caption = element_text(hjust = .5, size = 10, face = "italic"),
        legend.title = element_text(size = 10, face = "bold")) +
  labs(x = "Graduation Rate (%) - 2011",
       y = "",
       title = "State Graduation Rates",
       subtitle = "By Region and High School Physical Education Policy",
       caption = "DATA NOTE, INSERT NOTE THAT SOME STATES 
       WERE OMITTED DUE TO MISSING DATA (LIST THOSE STATES",
       color = "Region",
       shape = "HS PE Policy") +
  scale_shape_discrete(labels = 
                         c("0" = "No Requirement or Recommendation",
                           "2" = "90 min/wk Minimum",
                           "3" = "90 - 150 min/wk",
                           "4" = "150 - 225 min/wk",
                           "5" = "Requires 225 min/wk")) +
  guides(color = guide_legend(order = 1),
         shape = guide_legend(order = 2))
```


# Final Plots
```{r}
mapdata1 <- import(here("data", "dfz.xlsx"))
```

```{r}
scale.z <- mapdata1 %>% 
  group_by(stnam, avg_timehs2, fips) %>% 
  summarize(
    grad = mean(state_avg, na.rm = TRUE)) %>% 
  biscale::bi_class(x = grad, y = avg_timehs2, style = "quantile",
           dim = 2)

names(scale.z)[1] <- "full"
scale_join <- scale.z %>% left_join(usmap::statepop, by = "full")

plot.z <- usmap::plot_usmap(data = scale.z,
                            values = "bi_class",
                            labels = TRUE,
                            label_color = "white") +
  biscale::bi_scale_fill(pal = "GrPink", dim = 2, guide = F) +
  scale_x_continuous(breaks = NULL) +
  scale_y_continuous(breaks = NULL) +
  theme(plot.title = element_text(margin = margin(b = 8), 
                              color = "#ffffff",face = "bold",size = 9,
                              hjust = 0.5,
                              family = "Arial"),
    plot.subtitle = element_text(margin = margin(t=10,b = 25), 
                                 color = "#ffffff", size = 6, family = "Arial",
                                 hjust = 0.5),
    plot.caption =  element_text(margin = margin(t = 20), 
                                 color = "#ffffff", size = 5, family = "Arial",
                                 hjust = 0.95),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    legend.title = element_blank(),
    axis.text.x    = element_blank(),
    axis.text.y    = element_blank(),
    panel.background = element_blank(), 
    panel.grid.major = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.minor = element_blank(), 
    plot.background = element_rect(fill = "#f3f3f3", color = NA),
    panel.border = element_blank(),
    plot.margin = unit(c(1, 1, 1, 1), "cm"),
    axis.ticks = element_blank())

legend.z <- 
  biscale::bi_legend(pal = "GrPink",
                     dim = 2,
                     xlab = "Graduation Rate",
                     ylab = "PA Time Requirement",
                     size = 20) +
  theme(rect = element_rect(fill = "grey10"),
        panel.border = element_blank(),
        axis.text = element_blank(),
        plot.background = element_rect(fill = "#f3f3f3", color = NA),
        axis.title.x = element_text(size = 10,
                                    color = "#a1a1a1",
                                    face = "bold"),
        axis.title.y = element_text(size = 10,
                                    color = "#a1a1a1",
                                    face = "bold"),
        legend.text = element_text(size = 5),
        legend.text.align = 0)

ggdraw() +
  draw_plot(plot.z, 0, 0 , 1, 1) +
  draw_plot(legend.z, 0 , 0.1, 0.2, 0.2) + 
  draw_label("Source1: National Center for Education Statistics,
             Source 2: National Cancer Institute",
             color = "black", size = 7.5, angle = 0, x = 0.9, y = 0.05) + 
  draw_label("FILL IN LATER", 
             color = "black",
             size = 17,
             angle = 0,
             x = 0.5,
             y = 0.97,
             fontface = "bold") + 
  draw_label("
             Bivariate map showing the combination of the
             state physical activity requirements and the
             average graduation rate", 
             color = "black", size = 14, angle = 0, x =0.5, y = 0.92) + 
    theme(plot.background = element_rect(fill = "#f3f3f3", color = NA))
```

# WITH DIFFERENT COLOR PAL
__THIS WILL BE FINAL VERSION OF PLOT__
```{r}
z_pal <- biscale::bi_pal_manual(val_1_1 = "#D9FAFA", val_1_2 = "#7AB1B1",
val_2_1 = "#2BF7F7", val_2_2 = "#185252")

scale.z1 <- mapdata1 %>% 
  group_by(stnam, avg_timehs2, fips) %>% 
  summarize(
    grad = mean(state_avg, na.rm = TRUE)) %>% 
  biscale::bi_class(x = grad, y = avg_timehs2, style = "quantile",
           dim = 2)

names(scale.z1)[1] <- "full"
scale_join1 <- scale.z1 %>% left_join(usmap::statepop, by = "full")

plot.z1 <- usmap::plot_usmap(data = scale.z1,
                            values = "bi_class",
                            labels = TRUE,
                            label_color = "#ffffff") +
  biscale::bi_scale_fill(pal = z_pal, dim = 2, guide = "none") +
  scale_x_continuous(breaks = NULL) +
  scale_y_continuous(breaks = NULL) +
  theme(plot.title = element_text(margin = margin(b = 8), 
                              color = "#ffffff",face = "bold",size = 9,
                              hjust = 0.5,
                              family = "Arial"),
    plot.subtitle = element_text(margin = margin(t=10,b = 25), 
                                 color = "#ffffff", size = 6, family = "Arial",
                                 hjust = 0.5),
    plot.caption =  element_text(margin = margin(t = 20), 
                                 color = "#ffffff", size = 5, family = "Arial",
                                 hjust = 0.95),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    legend.title = element_blank(),
    axis.text.x    = element_blank(),
    axis.text.y    = element_blank(),
    panel.background = element_blank(), 
    panel.grid.major = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.minor = element_blank(), 
    plot.background = element_rect(fill = "white", color = NA), ##f3f3f3
    panel.border = element_blank(),
    plot.margin = unit(c(1, 1, 1, 1), "cm"),
    axis.ticks = element_blank())

legend.z1 <- 
  biscale::bi_legend(pal = z_pal,
                     dim = 2,
                     xlab = "Graduation Rate",
                     ylab = "PA Time Requirement",
                     size = 20) +
  theme(rect = element_rect(fill = "grey10"),
        panel.border = element_blank(),
        axis.text = element_blank(),
        plot.background = element_rect(fill = "#f3f3f3", color = NA),
        axis.title.x = element_text(size = 10,
                                    color = "#a1a1a1",
                                    face = "bold"),
        axis.title.y = element_text(size = 10,
                                    color = "#a1a1a1",
                                    face = "bold"),
        legend.text = element_text(size = 5),
        legend.text.align = 0)

ggdraw() +
  draw_plot(plot.z1, 0, 0 , 1, 1) +
  draw_plot(legend.z1, 0 , 0.1, 0.2, 0.2) + 
  draw_label("Source1 National Center for Education Statistics,
             Source 2 National Cancer Institute",
             color = "black", size = 7.5, angle = 0, x = 0.8, y = 0.05) + 
  draw_label("FILL IN LATER", 
             color = "black",
             size = 17,
             angle = 0,
             x = 0.5,
             y = 0.97,
             fontface = "bold") + 
  draw_label("
             Bivariate map showing the combination of the
             state physical activity requirements and the
             average graduation rate", 
             color = "black", size = 14, angle = 0, x =0.5, y = 0.92) + 
    theme(plot.background = element_rect(fill = "#f3f3f3", color = NA))
```


####################### End of Zach Viz #####################

############# Mandi Vizualization #####################





############## End Mandi Viz ###########################